require "json"
require "uri"
require "digest"
require "open-uri"
require "erb"

def calculate_sha_sum(version)
  uri = URI.parse("https://github.com/jathu/starfig/releases/download/#{version}/starfig-#{version}-macos-x86.zip")
  sha = Digest::SHA2.new

  puts "Downloading #{uri}..."
  open(uri, "rb") do |downloaded_file|
    puts "Calculating SHA256..."
    sha = Digest::SHA2.new
    File.open(downloaded_file.path) do |file|
      while chunk = file.read(256)
        sha << chunk
      end
    end
  end

  return sha.hexdigest
end

def generate_template(version, sha_sum)
  puts "Creating template with [version=#{version}] [sha256=#{sha_sum}]..."

  template = ERB.new <<-EOF
# DO NOT EDIT!
# This file was generated by "fx tool/brew/update" in the Starfig repo.

class Starfig < Formula
  desc "Starfig is a programmatic config generator. It helps create static configs using Starlark, a deterministic Python-like language."
  homepage "https://github.com/jathu/starfig"
  url "https://github.com/jathu/starfig/releases/download/<%= version %>/starfig-<%= version %>-macos-x86.zip"
  sha256 "<%= sha_sum %>"
  license "Apache-2.0"

  def install
    bin.install "starfig"
  end

  test do
    assert_match("starfig-<%= version %>", shell_output("\#{bin}/starfig version"))
  end
end
  EOF

  return template.result(binding)
end

if __FILE__ == $0
  args = JSON.parse(ARGV[0])
  version = args["version"]["value"]
  sha_sum = calculate_sha_sum(version)
  content = generate_template(version, sha_sum)
  puts "\n"
  puts content
end
