name: ci
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:    
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: lint, build & test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos-x86
          - os: ubuntu-20.04
            platform: linux-x86
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Lint Test
        run: test -z $(gofmt -l .)
      - name: Run Build
        run: go build ./...
      - name: Run Tests
        run: go test ./...
